---
abstract: 'Indian Numbering System representation'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7, CPAN::Meta::Converter version 2.141520'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-IND-Numbers
no_index:
  directory:
    - t
    - inc
requires:
  Moo: '0'
  bignum: '0'
  namespace::clean: '0'
  perl: '5.006'
resources:
  repository: https://github.com/Manwar/Lingua-IND-Numbers.git
version: '0.05'
